const soup=[
    {id:"1",
        name:"Sweet Corn Soup",
        price:"110",
    },
    {id:"2",
        name:"Tomato Corn Soup",
        price:"140",
    },
    {id:"3",
        name:"Tomato Soup",
        price:"100",
    },
    {id:"4",
        name:"Veg Manchow Soup",
        price:"150",
    },
    {id:"5",
        name:"Hot AndSour Soup",
        price:"130",
    },
    {id:"6",
        name:"MushroomSoup Soup",
        price:"120",
    },
    {id:"7",
        name:"VegClear Soup",
        price:"120",
    },
]

export default soup